### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by le-patenteux** [st-one-io/node-red-contrib-focas#4]
Hello, I am sorry but I looked around and I can't find how this module works and how to import it in Node-red
Can you point me to some documentation?
I am already connected to the CNC machines via Ethernet to push programs via FTP and The Focas network seems to be up.

Regards,

 - Normand

**Comment by pedrofrancescon** [comment]
Hi,

Currently this node can only be used on the ST-One hardware as it depends on another library developed by ST-One. That information was indeed missing on the README file though, so thank you for bringing that up.

**Comment by le-patenteux** [comment]
Thank you for those precisions.
The website is in a language I can't read... Where can I have info for pricing etc. for the ST-One Hardware?

**Comment by umeshk21** [comment]
I wonder what's the use for making this open when people can't use it openly?

**Comment by pedrofrancescon** [comment]
> I wonder what's the use for making this open when people can't use it openly?

Hi, sorry for the really late reply.

We usually make our nodes public to make it easier for us to install them later on the ST-One hardware. 
I'll close this issue, but fell free to contact us here again or by our [website](https://st-one.io/), we'll be glad to give further details.

Cheers.
